### PR TITLE
test utils now available as part of the jar

### PR DESCRIPTION
**Pull request by elisehuard**
These utilities are nice for people who want to write tests for apis written with compojure-api.  Just moved them from test to src basically.

[Review on Reviewable](https://reviewable.io/reviews/metosin/compojure-api/166)

### CODE REVIEW

**Comment by Deraen** [comment]
The test-utils would need some changes before they can be published as in public ns as they haven't been build with general use in mind.

- Docstrings
- Multiple arities instead of destructured rest parameter
- Some utilities are probably too restricted, like `raw-post*` now only allows setting few specified fields on the request.
    - Optional map to be merged to the request could make sense?

**Comment by elisehuard** [comment]
Thank you, that makes sense. I'll have a look when I have a little bit of time (probably not immediately).

**Comment by Deraen** [comment]
Thanks for the contribution, but we have decided to not merge this.

The current test utilities are not very well  designed and we don't want to expose them to to world as is.

Also, I think that test utilities should be packaged as a separate library. This way unnecessary dependencies (`peridot`) do not leak into uberjars and other production builds, and people wont "accidentally" use test utilities in application code.

**Comment by elisehuard** [comment]
Thanks, fair enough.

**Pull request closed without merging**
