### PR TITLE
add consumes and produces keys, at http verb level

### PR DESCRIPTION
**Pull request by zamaterian**
it's now possible to have different consumes/produces pr. route instead
only on api/context.

I'm currently working on extending compojure-api to work with Liberator.
When using liberator and compojure, your nomally define one route per liberator resource with the ANY macro, and the liberator key  :allowed-methods  [:get :put] restricts the http verbs. 

My current approach is a macro with the following parameters [path params liberator-resource swagger]
and compiles a GET* PUT* POST* based on the :allowed-methods in the liberator resource 
And then inject the right swagger keys into each form (eg. :body for PUT, POST, PATCH) and :produces  :consumes (not for GET) based on the liberator key :available-media-types. 

What I need to do right now is move the parsing* and schema validation of the request body from middleware into the :malformed? and again liberator should also validate the response body. 

Liberator should handle encoding and decoding of request/response body according to the :available-media-types. 

Do you have any suggestion on how to bypass the compojure-api middleware in the defapi and whats the best way of injecting schema validation based on status code into liberator's :malformed? and schema validation for the body ?  

Cheers 
Thomas

### CODE REVIEW

**Comment by ikitommi** [comment]
Ok, I think I understand. Might get complex as the current code created lexical bindings for the symbols into the body. If the validation is moved to somewhere else, the normal body will not see the coerced results. Is this ok? Could you share what would the end result look like, the source & generated code?

anyway, you could start by overriding the default restructure handlers (for `:body` etc.) so that instead of them defining a symbol with coerced value, they would define just a source code for that. You could then glue that code somewhere else.

you are the te @ freenode?

**Comment by ikitommi** [comment]
thanks!

**Comment by zamaterian** [comment]
My work in progress : 
https://gist.github.com/zamaterian/d83f3a2816ecbc54013e 

As I see I have to override / provide a custom defapi without api-middleware (since liberator handle encoding/decoding from a given mediatype)

**Comment by ikitommi** [comment]
Would it work if you just disable all the formats from `api`? Something like 

```clojure
(api
  {:formats []}
  ...
```

... the ring-middleware-format beneath should do nothing in that case. If it does, we could wire it so that it will be disabled totally when `:formats` is empty.

With `0.21.0`, one can override the produces & consumes for endpoints, so they would be the only source for those.

**Pull request merged**
