### PR TITLE
Give better error message when binding isn't valid. Fixes #354

### LINKED ISSUE #354: Better error message
## Library Version(s)
2.0.0-alpha9
## Problem
With a context like the following, 
```
 (context "/product/:id" []
          :coercion :spec
          :path-params [id ::id])
```
I get either 
```
CompilerException java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to clojure.lang.IObj, compiling:(/Users/erik/Documents/telenordigital.com/di-data-inventory/src/data_inventory/handler.clj:225:9) 
```
when I only evaluate this form, or 
```
CompilerException java.lang.ClassCastException, compiling:(/Users/erik/Documents/telenordigital.com/di-data-inventory/src/data_inventory/handler.clj:225:9)
```
when I evaluate the whole api. 

The root cause here is that I'm missing `:-` in the `path-params` bit.

### PR DESCRIPTION
**Pull request by slipset**
- Catch the exception thrown in `fnk-schema` and rethrow it with link
  to fnk-syntax

### CODE REVIEW

**Comment by ikitommi** [comment]
Looks good. 

Could you add a test that the new exception message is actually seen by the client? (similar exception tests in `compojure.api/integration_test` where I would add this too). Regression tests help keeping the codebase sane.

**Comment by slipset** [comment]
I'll add a test, but this isn't shown at runtime, but at compile-time.

**Comment by ikitommi** [comment]
Thanks! There is a compile-time check test [here](https://github.com/metosin/compojure-api/blob/115fa8fc9b1fb5e11729cafa49b02b538f411f72/test/compojure/api/integration_test.clj#L1084-L1092).

**Comment by slipset** [comment]
Thanks. I've added an integration test, but I could not make it pass.
There must be some midje-fu that I'm missing. 

Any pointers appreciated.

**Comment by ikitommi** [comment]
Sure, I'l try to fix. Thanks for the PR!

**Comment by ikitommi** [comment]
The `throws` expects a regex, fixed it. Added also a hint for the common(?) case of missing the `:-` with two parameters having a keyword as the second value. Looks now like this:

```clj
CompilerException java.lang.IllegalArgumentException: Binding is not valid, please refer to https://github.com/plumatic/plumbing/tree/master/src/plumbing/fnk#fnk-syntax
 for more information.

      binding: [id :compojure.api.integration-test/kikka]

 did you mean: [id :- :compojure.api.integration-test/kikka]
```

CompilerException java.lang.IllegalArgumentException: Binding is not valid, please refer to https://github.com/plumatic/plumbing/tree/master/src/plumbing/fnk#fnk-syntax
 for more information.

      binding: [id :compojure.api.integration-test/kikka]

https://github.com/metosin/compojure-api/commit/b9bcd2bc5809e9827e66b1d4a9d7f57339caf1ed

**Pull request merged**
