### PR TITLE
Allow api users to also define own handler for response validation errors

### PR DESCRIPTION
**Pull request by jkytomak**
We want to handle also response validation errors self,
so that we can log and notice invalid server data also from server logs in production and development.

### CODE REVIEW

**Comment by Deraen** [comment]
Could you revert the whitespace changes in api-middleware docstring?

**Comment by jkytomak** [comment]
Sure, but that means that right side is not aligned, because new key is so long

**Comment by Deraen** [comment]
Ah, didn't notice that. I don't like unnecessary changes but that's reason enough.

Looks good to me.

**Comment by ikitommi** [comment]
Overriding response coercion error handling is definetely a good thing, but I think it would be better to fix the mess beneath: input errors are handled in r-s and outputs in c-api. The new coercers in schema-tools allow the error type to be defined forehand. Both input & output coercion should use this and both should be handled in a same place & the overridable error-handler can create ring responses based on the type.

poking with r-s now, could try to cook up something on weekend.

**Comment by ikitommi** [comment]
or actually, if that made any sense, would love to see a non-breaking/migratable PR of it :)

**Comment by jkytomak** [comment]
I made changes:
now there is only one backward compatible error handler on compojure-api side
It gets also error-type and request as argument and swagger validation error type is hidden with compojure variants:
compojure.api.middleware/request-validation and compojure.api.middleware/reseponset-validation

**Comment by jkytomak** [comment]
Is this now ok or do you want some improvements still?
I didn't use schema-tools, because there you would need to make an exception again from an error so reverse the roles (which one is calling which one) on schema/coerce and schema/coerce! and potentially loose some information about original exception.
And the new common exception wrapper needed to be anyhow in compojure-api, because it does only have information about is the coercing done on request or response, so mapping of exception types could be also done there in one place.

**Comment by ikitommi** [comment]
we'll check this later today.

**Comment by ikitommi** [comment]
looking good. We would like to put all exception handling into a single place, so proposing few small changes:

- new mw in c-api, replaces both `rsm/wrap-validation-errors` & `wrap-exceptions`
- takes an options map, which has the exception `:type` values as keys and a handler fn as a value, with predefined values like:
   - `:compojure.api.middleware/request-validation`
   - `:compojure.api.middleware/response-validation`
   - `:compojure.api.middleware/default` (the default "catch everything else")

with defaults always merged in, one could override any of those or add custom domain exception types & handlers. +1 for the idea to pass request & type also in.

```clojure
(api
  {:exceptions {:mydomain.db/not-found not-found-handler
                :schema.core/error just-log-these-hander}}
  ...)
```

**Comment by jkytomak** [comment]
Made changes again.
It wasn't as simple as I anticipated, because different handlers handle different types of errors and maintaining backward compatibility was hard.
Hope this is more what you wanted.

**Comment by ikitommi** [comment]
Good stuff! Juho did some code moving aroung on top of these in #160. Would love to get your comments there too. We'll merge all of that to `0.23.0`.

Thanks!!

**Comment by Deraen** [comment]
@jkytomak Thanks for your contribution :) `[metosin/compojure-api "0.23.0-SNAPSHOT"]` is available in clojars, please test and tell if you have comments.

**Comment by jkytomak** [comment]
No problem. Checked master version, works fine with us.

**Pull request merged**
