### PR TITLE
Implement wrap-routes like in compojure.core which generates docs

### PR DESCRIPTION
**Pull request by Deraen**
`wrap-routes` uses now same kind of parameters as one in Compojure. Should we instead provide `wrap-routes` which uses the same kind of parameters as  our existing `middleware` (as in, middlewares defined  in vector)?

We probably shouldn't change existing `middleware` functionality as it would be breaking, even though hopefully no one is excepting it to apply middleware to routes outside of routes inside `middleware`.

### CODE REVIEW

**Comment by Deraen** [comment]
Notes:
- Remove `middleware` (we can't change how this works, but we can break existing code compile time)
- Create `wrap-middleware` which works like `wrap-routes` and takes options like `middleware`
- Add `:middleware` option to `defapi/api`, for global middlewares

**Comment by ikitommi** [comment]
Sounds like a small change, we could ship this with 1.2.0?

**Comment by Deraen** [comment]
`wrap-middleware` name doesn't make any sense if the arguments of new function will be `[middleware & body]`, like `middleware` has. `wrap-` prefix only makes sense if the function takes `handler` as the first argument.

**Comment by Deraen** [comment]
TODO:

- add tests to check that context middleware is applied even if handler is not matched
- rollback context? wrap-routes change
- `route-middleware` don't publish in `sweet`

**Pull request merged**
