### PR TITLE
sequence coercion for query params

### PR DESCRIPTION
**Pull request by jtmarmon**

### CODE REVIEW

**Comment by jtmarmon** [comment]
closes half of #115

**Comment by Deraen** [comment]
This should be possible to do using string->vector coercer.

**Comment by Deraen** [comment]
I implemented an alternative version in ring-swagger using Schema coercion.

**Comment by ikitommi** [comment]
Schema coercion is more elegant solution to this -> will bring this stuff to all ring-swagger client libs. Any plans for getting the WIP to DONE? Kinda need this now in my project...

**Comment by jtmarmon** [comment]
I originally wrote this in the ring-swagger lib, but decided ultimately to do it here because it doesn't make much sense in _most_ cases to coerce a string to a vector. for instance, if someone has a body param with schema `[String]` and the user sends a cardinality one, we want to reject that as an error, rather than blindly accept that. 

query params are the exception because there's no way to determine intent. i.e. `?name=steve` can't be intelligently resolved to a vector or string, where as json (what you would get in a POST body) supports the distinction of the types.

**Comment by jtmarmon** [comment]
anyone have any thoughts on the above? i think it's a better design decision to have this type of arbitrary logic in compojure-api

**Comment by Deraen** [comment]
The intent can be determined by inspecting the data and schema together, as schema coercien does.

E.g. With `?name=steve` and `[String]` coercion can see that the wanted type is collection and current collection is string and do `[x]` based on that.

That's how my branch works, it's currently a mess as I'm refactoring json-type multimethod, but I'll probably have this ready in few days.

**Comment by jtmarmon** [comment]
right, my suggestion was that it's better to keep that type of coercion localized to the parameter type. in other words, this coercion should only really happen with query params where _without_ knowing schema you can't understand intent. but i'm fine with it being in ring-swagger, just thought i'd give my 2 cents

**Comment by ikitommi** [comment]
There are two separate coercers in Ring-Swagger (and in Schema) - one for json and another for string-based formats (query & path). Compojure-api selects the coercer based on parameter type (string-coercer for path & query). So, both ways deliver the same end results. Except it also applies to path-parameters when pushed to R-S. And all other clients of R-S get it for free.

=> You are both right :) Ring-swagger is the right place for this.

**Comment by ikitommi** [comment]
Compojure-api chooses the coercer per parameter type. It's either `:json` or `:query`. Do we want this to apply to all of the `:query`-ones? I guess we do?

https://github.com/jtmarmon/compojure-api/blob/f2193625f480de70573cd3ea4e954471d8498f8a/src/compojure/api/meta.clj#L195-L264

**Comment by jtmarmon** [comment]
ahh i see. why are headers & form params etc parsed w/ the query parser? I would imagine it should only apply to query-param types for the aforementioned reason of the expressiveness (or lack thereof) of query strings

**Comment by Deraen** [comment]
Form params means content-type `application/x-www-form-urlencoded` in which case the request body is in same format as query string, so that makes sense.
Headers-params don't make as much sense.

**Comment by ikitommi** [comment]
how should header-params then be parsed? If one want's to send `user-id=123` header, I don't see a reason not to allow `:user-id` to be coerced into an `Integer`.

**Comment by ikitommi** [comment]
Thanks for the effort, but this got fixed in `0.21.0-SNAPSHOT` via ring-swagger.

**Pull request closed without merging**
